//! Generates the fixed-base window tables in `src/constants/tables.rs`.
//! Run with an absolute output path:
//! `FIXED_BASE_TABLES_OUT=$PWD/crates/circuit/src/constants/tables.rs cargo test
//! -p null-circuit --release --test gen_tables -- --ignored`.
//! Takes about 90 seconds; `fixed_bases.rs` checks the result.
#![allow(clippy::unwrap_used)]

use std::fmt::Write as _;

use group::Curve;
use halo2_gadgets::ecc::chip::constants::find_zs_and_us;
use halo2_gadgets::ecc::chip::{FixedScalarKind, FullScalar, ShortScalar};
use null_crypto::curve::Generator;

fn table(name: &str, base: Generator, windows: usize, out: &mut String) {
    let zs_us = find_zs_and_us(base.point().to_affine(), windows).unwrap();
    writeln!(out, "/// `z` per window for {base:?}.").unwrap();
    writeln!(out, "pub const {name}_Z: [u64; {windows}] = [").unwrap();
    for (z, _) in &zs_us {
        writeln!(out, "    {z},").unwrap();
    }
    writeln!(out, "];\n").unwrap();
    writeln!(
        out,
        "/// `u` per window for {base:?}, as little-endian field elements."
    )
    .unwrap();
    writeln!(out, "pub const {name}_U: [[[u8; 32]; H]; {windows}] = [").unwrap();
    for (_, us) in &zs_us {
        writeln!(out, "    [").unwrap();
        for u in us {
            let bytes: [u8; 32] = ff::PrimeField::to_repr(u);
            let hex: Vec<String> = bytes.iter().map(|b| format!("{b:#04x}")).collect();
            writeln!(out, "        [{}],", hex.join(", ")).unwrap();
        }
        writeln!(out, "    ],").unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

#[test]
#[ignore = "regenerates the committed tables"]
fn generate_fixed_base_tables() {
    let Ok(path) = std::env::var("FIXED_BASE_TABLES_OUT") else {
        return;
    };
    let start = std::time::Instant::now();
    let mut out = String::new();
    writeln!(
        out,
        "//! Fixed-base window tables, generated by `tests/gen_tables.rs`."
    )
    .unwrap();
    writeln!(
        out,
        "//! Do not edit; `tests/fixed_bases.rs` checks them against the generators.\n"
    )
    .unwrap();
    writeln!(out, "use halo2_gadgets::ecc::chip::H;\n").unwrap();
    table(
        "SPEND_AUTH",
        Generator::SpendAuth,
        FullScalar::NUM_WINDOWS,
        &mut out,
    );
    table(
        "VALUE_COMMIT_R",
        Generator::ValueCommitRandom,
        FullScalar::NUM_WINDOWS,
        &mut out,
    );
    table(
        "VALUE_COMMIT_V",
        Generator::ValueCommitValue,
        ShortScalar::NUM_WINDOWS,
        &mut out,
    );
    std::fs::write(path, out).unwrap();
    eprintln!("generated in {:?}", start.elapsed());
}
